# Generated by Django 3.1.2 on 2020-10-25 11:02

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201025_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mass',
            field=models.IntegerField(blank=True, null=True, validators=[myapp.models.validate_weight]),
        ),
    ]
